### PR TITLE
Create journal-week-4.md

### PR DESCRIPTION
**Pull request by karjac14**

### CODE REVIEW

**Comment by drumslayert** [comment]
please don't remind me of last week!!! :+1:

**Comment by drumslayert** [comment]
don't forget your tutorial!

**Comment by rosalsm** [comment]
Good journal week 4 Karlo :+1: 

Large tutorial draft, it looks like MVC is still fresh after your beautiful chess board :+1:

**Comment by jeremyrist** [comment]
:+1: Great tutorial! Super helpful, we talked today about it but I'm glad to see it in writing now

**Comment by ericquayson** [comment]
Great tutorial Karlo! I will definitely be reading this when you're finish with it

**Comment by nickycadavillo** [comment]
:+1: I like the journal entry.  This tutorial is also looking great.  Super informative!  I will definitely be referencing this in the future.

**Comment by Ricecoder** [comment]
Thanks for the great tutorial on MVC! I am sure I will be referencing it often as we move forward in class. Good job! :+1:

**Comment by ericksonk** [comment]
I agree, Sass makes CSS easier! Take out the extra "that" in the last sentence of your journal and it will be looking pretty good :+1:

**Comment by cmauban** [comment]
Such a great tutorial! It'll definitely be useful when I go back to fix my chessboard! :+1:

**Comment by jeremyrist** [comment]
:+1: I agree on the sass stuff, much easier to wrap my head around. Fun working today!

**Comment by drumslayert** [comment]
great start on your tutorial! Javascript King! :+1:

**Comment by ShayHall** [comment]
:+1: Good stuff.  I think that's helpful to point out that splitting the screen to see html and scss next to one another is helpful in understanding nesting.  I also liked the way you gave examples in your tutorial for the MVC.

**Comment by boshnivolo** [comment]
I'm going to have to get you to help me with some jQuery! Great journal, Karlo! :+1:

**Comment by drumslayert** [comment]
Nice work on the MVC Karlo! It's a very informative read, but maybe next time narrow it down to something specific and teach us step by step how "to do" that. You could literally make a tutorial on each one of your points. Like "Properly identify the elements to be used in the html and assign classes and ids." You could show us how to perform those tasks in a step by step process.  Just some ideas for you to throw around for next time buddy. :+1:

**Pull request merged**
