### PR TITLE
Feature responsive specs

### PR DESCRIPTION
**Pull request by karjac14**

### CODE REVIEW

**Comment by drumslayert** [comment]
Whoa you got a lot a skitch! :+1:

**Comment by Ricecoder** [comment]
It looks like you have the squares for the layout but you might want to think about adding some html notes like tags or possible classes. :+1:

**Comment by karjac14** [comment]
for some reason, the mobile view cannot be captured. I will figure out later.

I also think that should have not commited the unmarked images. but its already there.

**Comment by karjac14** [comment]
thanks for the heads up Lacey!

**Pull request merged**
