### PR TITLE
Flows of Ideas

### PR DESCRIPTION
**Pull request by karjac14**

### CODE REVIEW

**Comment by nickycadavillo** [comment]
:+1:  Great start, Karlo!  I especially liked your first paragraph on your reflection of the week!

**Comment by Ricecoder** [comment]
:+1: Good job! I appreciate the tutorial on the box-sizing. That is something I struggle with.

**Comment by jeremyrist** [comment]
Box-sizing: Border-Box! Thanks for the tutorial! :+1:

**Comment by boshnivolo** [comment]
Your Tutorial is coming along. I like the how you included that code fenced area in it as well. :+1:

**Comment by nickycadavillo** [comment]
:+1: Looks great, Karlo!

**Comment by cmauban** [comment]
Nice tutorial! :+1: Looking forward to hearing more about box-sizing since I'm still fuzzy on that!

**Comment by boshnivolo** [comment]
Yeah, completing most of an assignment is always really refreshing lol great journal! :+1:

**Comment by ShayHall** [comment]
Looks like you have the remains of a merge conflict hanging out in your journal.  Look over it again and take out the repetitions and the `HEAD<<<<<<<<<<<<<<<` stuff.  Otherwise, it looks good.  I like that you put the note in the tutorial that there may be some unintended side effects to putting box-sizing:border-box on everything. :+1:

**Pull request merged**
